"""Add skin type columns to users and create product_analyses table

Revision ID: 4ce5ba3c2910
Revises: 
Create Date: 2025-06-30 19:37:47.708342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce5ba3c2910'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skin_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skin_assessment_answers', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('skin_concerns', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skin_concerns')
    op.drop_column('users', 'skin_assessment_answers')
    op.drop_column('users', 'skin_type')
    # ### end Alembic commands ###
