import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  Share,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { StatusBar } from 'expo-status-bar';
import Ionicons from '@expo/vector-icons/Ionicons';

export default function AnalysisResultScreen({ navigation, route }) {
  const { analysis } = route.params;
  const result = analysis.analysis_result || {};

  const getSuitabilityColor = (score) => {
    if (score >= 8) return '#00ff88';
    if (score >= 6) return '#ffaa00';
    if (score >= 4) return '#ff6600';
    return '#ff4444';
  };

  const getSuitabilityText = (score) => {
    if (score >= 8) return 'Highly Suitable';
    if (score >= 6) return 'Moderately Suitable';
    if (score >= 4) return 'Use with Caution';
    return 'Not Recommended';
  };

  const shareAnalysis = async () => {
    try {
      const shareContent = `
SkinSenseAI Analysis Report

Product: ${analysis.product_name || 'Unknown Product'}
Brand: ${result.brand || 'Unknown'}
Suitability Score: ${analysis.suitability_score}/10
Status: ${getSuitabilityText(analysis.suitability_score)}

Recommendation: ${analysis.recommendation || 'No recommendation available'}

${analysis.warnings ? `Warnings: ${analysis.warnings}` : ''}

Generated by SkinSenseAI
      `.trim();

      await Share.share({
        message: shareContent,
        title: 'Product Analysis Report',
      });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  return (
    <SafeAreaView className="flex-1">
      <StatusBar style="light" />
      <LinearGradient
        colors={['#000000', '#1a1a1a', '#000000']}
        className="flex-1"
      >
        <ScrollView className="flex-1" showsVerticalScrollIndicator={false}>
          {/* Header */}
          <View className="px-6 pt-1 pb-6">
            <View className="flex-row justify-between items-center mb-6">
              <TouchableOpacity
                onPress={() => navigation.goBack()}
                className="w-12 h-12 rounded-full items-center justify-center"
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.05)',
                  borderWidth: 1,
                  borderColor: 'rgba(255, 255, 255, 0.1)',
                }}
              >
                <Ionicons name="arrow-back" size={24} color="white" />
              </TouchableOpacity>

              <TouchableOpacity
                onPress={shareAnalysis}
                className="w-12 h-12 rounded-full items-center justify-center"
                style={{
                  backgroundColor: 'rgba(0, 245, 255, 0.1)',
                  borderWidth: 1,
                  borderColor: 'rgba(0, 245, 255, 0.2)',
                }}
              >
                <Ionicons name="share-outline" size={24} color="#00f5ff" />
              </TouchableOpacity>
            </View>

            <Text className="text-3xl font-bold text-white mb-2">
              Analysis Result
            </Text>
            <Text className="text-gray-300 text-lg">
              Product suitability report
            </Text>
          </View>

          <View className="px-6 space-y-6">
            {/* Product Info */}
            <View 
              className="rounded-2xl p-6"
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.03)',
                borderWidth: 1,
                borderColor: 'rgba(255, 255, 255, 0.08)',
              }}
            >
              <Text className="text-xl font-bold text-white mb-2">
                {analysis.product_name || 'Product Analysis'}
              </Text>
              
              {result.brand && (
                <Text className="text-gray-400 text-lg mb-2">
                  {result.brand}
                </Text>
              )}

              {result.product_type && (
                <Text className="text-gray-400 text-sm mb-2">
                  {result.product_type}
                </Text>
              )}
              
              {analysis.created_at && (
                <Text className="text-gray-400 text-sm mb-4">
                  Analyzed on {new Date(analysis.created_at).toLocaleDateString()}
                </Text>
              )}

              {/* Suitability Score */}
              <View className="items-center mb-4">
                <View 
                  className="w-24 h-24 rounded-full items-center justify-center mb-3"
                  style={{
                    backgroundColor: `${getSuitabilityColor(analysis.suitability_score)}20`,
                    borderWidth: 3,
                    borderColor: getSuitabilityColor(analysis.suitability_score),
                  }}
                >
                  <Text 
                    className="text-2xl font-bold"
                    style={{ color: getSuitabilityColor(analysis.suitability_score) }}
                  >
                    {analysis.suitability_score}
                  </Text>
                  <Text 
                    className="text-sm font-medium"
                    style={{ color: getSuitabilityColor(analysis.suitability_score) }}
                  >
                    /10
                  </Text>
                </View>
                <Text 
                  className="text-lg font-semibold"
                  style={{ color: getSuitabilityColor(analysis.suitability_score) }}
                >
                  {getSuitabilityText(analysis.suitability_score)}
                </Text>
              </View>
            </View>

            {/* Recommendation */}
            {analysis.recommendation && (
              <View 
                className="rounded-2xl p-4"
                style={{
                  backgroundColor: 'rgba(0, 245, 255, 0.05)',
                  borderWidth: 1,
                  borderColor: 'rgba(0, 245, 255, 0.1)',
                }}
              >
                <View className="flex-row items-center mb-3">
                  <Ionicons name="bulb-outline" size={20} color="#00f5ff" />
                  <Text className="text-cyan-400 font-semibold ml-2 text-lg">
                    Recommendation
                  </Text>
                </View>
                <Text className="text-gray-300 leading-relaxed">
                  {analysis.recommendation}
                </Text>
              </View>
            )}

            {/* Warnings */}
            {analysis.warnings && (
              <View 
                className="rounded-2xl p-4"
                style={{
                  backgroundColor: 'rgba(255, 102, 0, 0.05)',
                  borderWidth: 1,
                  borderColor: 'rgba(255, 102, 0, 0.1)',
                }}
              >
                <View className="flex-row items-center mb-3">
                  <Ionicons name="warning-outline" size={20} color="#ff6600" />
                  <Text className="text-orange-400 font-semibold ml-2 text-lg">
                    Warnings
                  </Text>
                </View>
                <Text className="text-gray-300 leading-relaxed">
                  {analysis.warnings}
                </Text>
              </View>
            )}

            {/* Key Ingredients */}
            {result.key_ingredients && result.key_ingredients.length > 0 && (
              <View 
                className="rounded-2xl p-4"
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.03)',
                  borderWidth: 1,
                  borderColor: 'rgba(255, 255, 255, 0.08)',
                }}
              >
                <View className="flex-row items-center mb-3">
                  <Ionicons name="list-outline" size={20} color="white" />
                  <Text className="text-white font-semibold ml-2 text-lg">
                    Key Ingredients
                  </Text>
                </View>
                <View className="space-y-2">
                  {result.key_ingredients.map((ingredient, index) => (
                    <View key={index} className="flex-row items-center">
                      <Ionicons name="ellipse" size={8} color="#00f5ff" />
                      <Text className="text-gray-300 ml-2 capitalize">
                        {ingredient}
                      </Text>
                    </View>
                  ))}
                </View>
              </View>
            )}

            {/* Beneficial Ingredients */}
            {result.beneficial_ingredients && result.beneficial_ingredients.length > 0 && (
              <View 
                className="rounded-2xl p-4"
                style={{
                  backgroundColor: 'rgba(0, 255, 136, 0.05)',
                  borderWidth: 1,
                  borderColor: 'rgba(0, 255, 136, 0.1)',
                }}
              >
                <View className="flex-row items-center mb-3">
                  <Ionicons name="leaf-outline" size={20} color="#00ff88" />
                  <Text className="text-green-400 font-semibold ml-2 text-lg">
                    Beneficial Ingredients
                  </Text>
                </View>
                <View className="space-y-2">
                  {result.beneficial_ingredients.map((ingredient, index) => (
                    <View key={index} className="flex-row items-start">
                      <Ionicons name="checkmark-circle" size={16} color="#00ff88" style={{ marginTop: 2 }} />
                      <Text className="text-gray-300 ml-2 flex-1">
                        {ingredient}
                      </Text>
                    </View>
                  ))}
                </View>
              </View>
            )}

            {/* Problematic Ingredients */}
            {result.problematic_ingredients && result.problematic_ingredients.length > 0 && (
              <View 
                className="rounded-2xl p-4"
                style={{
                  backgroundColor: 'rgba(255, 68, 68, 0.05)',
                  borderWidth: 1,
                  borderColor: 'rgba(255, 68, 68, 0.1)',
                }}
              >
                <View className="flex-row items-center mb-3">
                  <Ionicons name="alert-circle-outline" size={20} color="#ff4444" />
                  <Text className="text-red-400 font-semibold ml-2 text-lg">
                    Ingredients to Watch
                  </Text>
                </View>
                <View className="space-y-2">
                  {result.problematic_ingredients.map((ingredient, index) => (
                    <View key={index} className="flex-row items-start">
                      <Ionicons name="warning" size={16} color="#ff4444" style={{ marginTop: 2 }} />
                      <Text className="text-gray-300 ml-2 flex-1">
                        {ingredient}
                      </Text>
                    </View>
                  ))}
                </View>
              </View>
            )}

            {/* Usage Tips */}
            {result.usage_tips && (
              <View 
                className="rounded-2xl p-4"
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.03)',
                  borderWidth: 1,
                  borderColor: 'rgba(255, 255, 255, 0.08)',
                }}
              >
                <View className="flex-row items-center mb-3">
                  <Ionicons name="information-circle-outline" size={20} color="white" />
                  <Text className="text-white font-semibold ml-2 text-lg">
                    Usage Tips
                  </Text>
                </View>
                <Text className="text-gray-300 leading-relaxed">
                  {result.usage_tips}
                </Text>
              </View>
            )}

            {/* Action Buttons */}
            <View className="space-y-4 pb-8">
              <TouchableOpacity
                onPress={() => navigation.navigate('ProductAnalysis')}
                className="rounded-2xl py-4 overflow-hidden"
              >
                <LinearGradient
                  colors={['#00f5ff', '#0080ff', '#8000ff']}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 0 }}
                  className="py-4 rounded-2xl"
                >
                  <Text className="text-black text-center text-lg font-bold">
                    Analyze Another Product
                  </Text>
                </LinearGradient>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => navigation.navigate('MyAnalyses')}
                className="rounded-2xl py-4"
                style={{
                  backgroundColor: 'rgba(255, 255, 255, 0.05)',
                  borderWidth: 1,
                  borderColor: 'rgba(255, 255, 255, 0.1)',
                }}
              >
                <Text className="text-white text-center text-lg font-semibold">
                  View All Analyses
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        </ScrollView>
      </LinearGradient>
    </SafeAreaView>
  );
}